In [11]:
a,b,c = 10,11,12
print(a+b+c)

33

In [25]:
a = 10**3
a

1000

In [23]:
a = int(input("Enter the length of the cuboid:"))
b = int(input("Enter the breadth of the cuboid:"))
c = int(input("Enter the height of the cuboid:"))
d = 2*((a*b) + (b*c) + (c*a))

print("The surface area of cuboid is: ",d)

Enter the length of the cuboid: 15
Enter the breadth of the cuboid: 34
Enter the height of the cuboid: 21

The surface area of cuboid is:  3078

In [1]:
a = 3 + 4j
type(a)

complex

# CONDITIONALS

In [11]:
a = int(input("Enter the 1st number:"))
b = int(input("Enter the 2nd number:"))
c = int(input("Enter the 3rd number:"))

if a > (b and c):
    print("The 1st number is greatest")
elif b > (a and c):
    print("The 2nd number is greatest")

elif a == b ==c:
    print("The numbers are equal")
else:
    print("The 3rd number is greatest")

Enter the 1st number: 33
Enter the 2nd number: 34
Enter the 3rd number: 33

The 2nd number is greatest

# Nested If

In [13]:
a = int(input("Enter the 1st number:"))
b = int(input("Enter the 2nd number:"))

if a > b:
    print("The difference between the numbers is:", a-b)

else:
    print("The difference between the numbers is:", b-a)

Enter the 1st number: 33
Enter the 2nd number: 12

The difference between the numbers is: 21

In [21]:
# Input two numbers
a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))

# Using nested if
if a != b:
    if a > b:
        diff = a - b
    else:
        diff = b - a
    print("The difference between the two numbers is:", diff)
else:
    print("Both numbers are equal, so the difference is 0.")

Enter the first number:  12
Enter the second number:  45

The difference between the two numbers is: 33

In [24]:
# Find if any of the number inserted by user is even or odd.

a = int(input("Enter the first number: "))

if a % 2 == 0:
    print("The 1st number is even")

else:
    print("The 1st number is odd")

Enter the first number:  33

The 1st number is odd

In [26]:
# Find the eligibillity of voter to cast vote.

a = int(input("Enter the age: "))

if a >= 18:
    print("Eligible to vote")

else:
    print("Not Eligible")

Enter the age:  18

Eligible to vote

In [30]:
# Check if marks of a subject are within range (0-100)

a = int(input("Enter the marks: "))

if a >= 0 and a<= 100:
    print("Valid marks")

else:
    print("Invalid marks")

Enter the marks:  100

Valid marks

In [36]:
# Check if a student has passsed or failed by taking marks in 3 subjects.

a = int(input("Enter the marks in 1st subject:"))
b = int(input("Enter the marks in 2nd subject:"))
c = int(input("Enter the marks in 3rd subject:"))

if (a or b or c) >= 40:
    print("pass")

else:
    print("fail")

Enter the marks in 1st subject: 45
Enter the marks in 2nd subject: 55
Enter the marks in 3rd subject: 65

pass

In [ ]:
# check is a person is authorised for admin access or not.
# check if given lower case character is a vowel or consonant.
# Check if number input is positive, negative or zero.
# Accept students marks and assign grade to them according to marks.
# Check if any nu,ber is divisible by 3 and 5 both. if divisible print "Yes" if only by 3 print "buzz" if only by 5 print "fizz"
# Write a Python program to check the age group of a person - 0-12 : child, 13-19 : Teenage, 20-60 : adult, 60 above : senior
# Take three sides of a triangle as input and check whether they form a valid triangle. 
# Note for previous question : A triangle is valid if the sum of any two sides is greater than the third side.
# Accept three numbers as input and find the greatest among them.
# Write a program to calculate the electricity bill based on the following:
'''Units ≤ 100: ₹5/unit
101–200 units: ₹7/unit
Above 200 units: ₹10/unit'''

In [ ]:
# check is a person is authorised for admin access or not.

a = int(input("Enter the age: "))

In [ ]:
# Check if number input is positive, negative or zero.

a = int(input("Enter the number:"))

if a == "-":
    print("")

# Loops

In [ ]:
# while loop
# While loop questions

# Multiplication table for any given integer

# Do all of these given tasks for a given number :
    # 1- count the number of digits in the number
    # 2- Find digital sum of that number
    # 3- Reverse the number
    # 4- Check if number is palindromic number

# Do all of these given tasks for a given number :
    # 1- Find the sum of given numbers
    # 2- Find sum of positive and negative numbers
    # 3- Find maximum number from given numbers
    # 4- Convert a decimal number to binary number

# Create a program which will allow user to guess a number between 1-10.
# Note  for previous que : 
    # 1 - if this number matches with guess of computer then it will show correct answer otherwise more chances will be given to user
    # 2- Use import random to and number=random.randint(1,10) for computer to pick and random number

# Write a program where the computer randomly selects a word from a predefined list (["cat", "dog", "fish", "bird", "snake"]), and the user has to guess the word.  
    #- The user has unlimited chances.  
    #- Provide a hint about the length of the word after each incorrect guess.
# Create a program where the user has to guess a number between 1 and 50.  
    #- The computer gives feedback ("higher" or "lower") for each incorrect guess.  
    #- The game ends when the correct number is guessed.  
    #- Count and display the total number of attempts when the user wins.

# Simulate a dice-rolling game where the user must guess the outcome of a 6-sided die roll.  
    #- Use random.randint(1, 6) to generate the dice roll.  
    #- The user gets only 3 attempts to guess the correct number.  
    #- If the user fails, display the correct number.

# Write a program where the computer randomly generates a number between 1 and 100.  
    #- The user has to guess whether the number is odd or even by typing "odd" or "even."  
    #- Provide feedback after each guess, and allow 5 total guesses.  
    #- Display the correct answer if the user fails.

# Create a program that randomly generates a simple addition or subtraction question (e.g., 5 + 3 or 9 - 4).  
    #- Use random.randint(1, 20) to generate two random numbers and decide the operation.  
    #- The user has to provide the correct answer within 3 attempts.  
    #- After 3 incorrect answers, display the correct answer and exit.

In [1]:
i = 1
while i<=5:
    print(i)
    i += 1

1
2
3
4
5

In [6]:
a = int(input("Enter the number:"))
i = 1
while i<=10:
    print(f"{a} x {i} = {a*i}")
    i += 1

Enter the number: 6

6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60

In [9]:
a = int(input("Enter the number:"))
for i in range(1,11):
    print(a*i)

Enter the number: 83

83
166
249
332
415
498
581
664
747
830

In [14]:
for i in range(10,-1,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1
0

In [21]:
a = "HELLOWORLD"
for i in a:
    print(i)

H
E
L
L
O
W
O
R
L
D

In [ ]:
# Do all of these given tasks for a given number :
    # 1- count the number of digits in the number
    # 2- Find digital sum of that number
    # 3- Reverse the number
    # 4- Check if number is palindromic number

In [10]:
#1
a = int(input("Enter the number:"))
i=0
while a>0:  
    i = i+1
    a //=10
print(i)

Enter the number: 87364

5

In [6]:
#2
num = int(input("Enter the number:"))
digital_sum = 0
j = 0
while num>0:
    j = num%10
    digital_sum = digital_sum + j
    num //= 10

print(digital_sum)

Enter the number: 999

27

In [26]:
#3
n = int(input("Enter the number:"))
rev = 0
while n>0:
    r = n%10
    n = n//10
    rev = rev*10 + r

print(rev)

Enter the number: 091

19

In [29]:
n = input("Enter the number:")   # take input as string, not int
i = len(n) - 1                   # start from the last index
rev = ""                         # empty string to store reversed number

while i >= 0:
    rev = rev + n[i]             # add each digit from end
    i -= 1                       # move to the previous character

print("Reversed number:", rev)

Enter the number: 120

Reversed number: 021

In [1]:
#4
n = int(input("Enter the number:"))

temp = n
rev = 0
while n>0:
    r = n%10
    n = n//10
    rev = rev*10 + r

if temp == rev:
    print("Palindrome")
else:
    print("Not")

Enter the number: 120

Not

In [ ]:
# Do all of these given tasks for a given number :
    # 1- Find the sum of given numbers
    # 2- Find sum of positive and negative numbers
    # 3- Find maximum number from given numbers
    # 4- Convert a decimal number to binary number

In [32]:
#1
n = int(input("Enter the number:"))
Sum = 0
j = 0
while n>0:
    j = n%10
    Sum = Sum + j
    n = n//10

print(Sum)

Enter the number: 123

6

In [34]:
#2
sum1 = 0
sum2 = 0
while True:
    n = int(input("Enter the number(Enter 0 to stop):"))
    if n > 0:
        sum1 = sum1 + n
    elif n == 0:
        break
    else:
        sum2 = sum2 + n

print(sum1)
print(sum2)

Enter the number(Enter 0 to stop): 2
Enter the number(Enter 0 to stop): 3
Enter the number(Enter 0 to stop): 5
Enter the number(Enter 0 to stop): -4
Enter the number(Enter 0 to stop): -2
Enter the number(Enter 0 to stop): -8
Enter the number(Enter 0 to stop): 0

10
-14

In [36]:
# 3- Find maximum number from given numbers
n = int(input("How many number you want to enter:"))
i = 1
while n>=i:
    n = int(input("Enter the number(Enter 0 to break):"))
    if n == 0:
        break
    elif n > n:
        i = i + n
    else:
        print("invalid")

print(i)

Enter the number(Enter 0 to break): 8

invalid

Enter the number(Enter 0 to break): 6

invalid

Enter the number(Enter 0 to break): 5

invalid

Enter the number(Enter 0 to break): -9

invalid

Enter the number(Enter 0 to break): -4

invalid

Enter the number(Enter 0 to break): 0

0

In [8]:
# 4- Convert a decimal number to binary number
n = int(input("Enter the decimmal number"))
B = ""
while n>0:
    r = n%2
    B = B + str(r)
    n = n//2

print(B)

Enter the decimmal number 9

1001

In [9]:
# Create a program which will allow user to guess a number between 1-10.
# Note  for previous que : 
    # 1 - if this number matches with guess of computer then it will show correct answer otherwise more chances will be given to user
    # 2- Use import random to and number=random.randint(1,10) for computer to pick and random number

Enter a decimal number:  9

Binary number is: 1001

In [12]:
# Create a program which will allow user to guess a number between 1-10.

Guess a number between 1 and 10:  5

Too low! Try again.

Guess again:  7

Too low! Try again.

Guess again:  9

Too high! Try again.

Guess again:  8

🎉 Congratulations! You guessed it right!

In [2]:
print(1%10)
print(9//2)

1
4

In [17]:
num = int(input("Enter a number: "))
fact = 1

for i in range(1, num + 1):
    fact = fact * i

print(f"The factorial of {num} is {fact}")

Enter a number:  44

The factorial of 44 is 2658271574788448768043625811014615890319638528000000000

In [4]:
# Input from user
a = int(input("Enter the first term (a): "))
d = int(input("Enter the common difference (d): "))
n = int(input("Enter the number of terms (n): "))

print("The Arithmetic Progression is:")

# Print the AP terms
for i in range(n):
    term = a + i * d
    print(term, end=" ")

# Find and print the nth term
nth_term = a + (n - 1) * d
print(f"\nThe {n}th term of the AP is: {nth_term}")

Enter the first term (a):  12
Enter the common difference (d):  2
Enter the number of terms (n):  8

The Arithmetic Progression is:
12 14 16 18 20 22 24 26
The 8th term of the AP is: 26

In [20]:
num = int(input("Enter the number:"))
count = 0
while num>0:
    count += 1
    num = num//10

print(f"The count of the number is {count}")

Enter the number: 92734

The count of the number is 5

In [3]:
for i in range(1,10):
    if i == 3:
        continue
    else:
        print(i)

1
2
4
5
6
7
8
9

# Nested Loop

In [6]:
for i in range(1,4):
    for j in range(0,5):
        print(i,j)

1 0
1 1
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 1
3 2
3 3
3 4

# Strings

In [19]:
chr(2744)

'સ'

In [24]:
a = "Men in black"
a.find("o")

-1

In [23]:
a.index("0")

ValueError: substring not found

In [28]:
a.rjust(1)

'Men in black'

In [27]:
l = [1,2,3,4,5,6]
for x in l:
    print(x)

1
2
3
4
5
6

In [3]:
for x in range(len(l)):
    print(x)

0
1
2
3
4
5

In [9]:
for x in range(len(l)-1,-1,-1):
    print(l[x])

6
5
4
3
2
1

In [11]:
i = 0
while i<len(l):
    print(l[i])
    i += 1

1
2
3
4
5
6

In [12]:
l.append(7)
print(l)

[1, 2, 3, 4, 5, 6, 7]

In [17]:
l.insert(1,13)
l

[1, 13, 2, 3, 4, 5, 6]

In [19]:
l.pop(1)
l

[1, 2, 3, 4, 5, 6]

In [22]:
l

[1, 2, 3, 4, 5, 6]

In [25]:
del l[3]

In [28]:
l

[1, 2, 3, 4, 5, 6]

In [36]:
l = [[1,2], [3,4], [5,6]]
print(l[1][1])

4

In [35]:
l[1:2]

[[3, 4]]

In [47]:
l = [10, 20, 30, 40, 50]
print(l)

[10, 20, 30, 40, 50]

In [51]:
l[::-1]

[50, 40, 30, 20, 10]

In [56]:
# Extract every second element from the list [1, 2, 3, 4, 5, 6, 7, 8] using slicing
l = [1, 2, 3, 4, 5, 6, 7, 8]
l[1::2]

[2, 4, 6, 8]

In [57]:
l = [10, 20, 30, 40, 50]
l[1:3]=[90,100,101]
l

[10, 90, 100, 101, 40, 50]

In [12]:
l1 = [10, 20, 30, 40, 50]
l2 = [1, 2, 3, 4, 5, 6]

l1.extend(l2)
l1

[10, 20, 30, 40, 50, 1, 2, 3, 4, 5, 6]

In [13]:
l1 = [10, 20, 30, 40, 50]
l2 = [1, 2, 3, 4, 5, 6]

for i in l2:
    l1.append(i)
    print(l1)

[10, 20, 30, 40, 50, 1]
[10, 20, 30, 40, 50, 1, 2]
[10, 20, 30, 40, 50, 1, 2, 3]
[10, 20, 30, 40, 50, 1, 2, 3, 4]
[10, 20, 30, 40, 50, 1, 2, 3, 4, 5]
[10, 20, 30, 40, 50, 1, 2, 3, 4, 5, 6]

In [27]:
l=[0]
l=l*100
l

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [28]:
l[9::10]=[1]*10
l

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1]

In [39]:
l=[2,4]
l2=[1,2,3,4,5]
if l[0] in l2:
    print("True")
elif l[1] in l2:
    print("true")

else:
    print("False")

True

In [38]:
l=[2,3]
l2=[1,2,3,4,5]
l[0] in l2

False

In [40]:
l=[2,4]
l2=[1,2,3,4,5]
for i in l:
    if i in l2:
        print(i,"true")
    else:
        print(i, "False")

2 true
4 true

In [6]:
l = [1,2,3,4,5,6,4]
l.index(4)

3

In [7]:
l.index(4,4,7)

6

In [13]:
l = [1,2,3,5,2,4,3,2,1,2,3,3,6,8,9,7,6,6,8,8,7]
l.count(5)

1

In [15]:
l.reverse()
l

TypeError: list.reverse() takes no keyword arguments

In [23]:
l.sort(reverse = True)
l

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [41]:
l=[]
i=1
for i in range(2,11,2):
    l.append(i)

In [42]:
l

[2, 4, 6, 8, 10]

In [50]:
l=[]

for i in range(11):
    i = i**2
    l.append(i)

In [51]:
l

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [52]:
l="@jhhbigf65463$@%#"
for i in

'@jhhbigf65463$@%#'

In [54]:
l = [int(i) for i in input("Enter the working hours:").split()]
l

Enter the working hours: 2 3 4 5

ValueError: invalid literal for int() with base 10: ' '

In [59]:
l = [int(i) for i in input("Enter the number:").split() if i == i]

Enter the number: 2 3 4 5 6 7 7 8 7 6 5 4 3 3 3 5 5 8 9 6 5 5 7 5  3 5

In [60]:
l

[2, 3, 4, 5, 6, 7, 7, 8, 7, 6, 5, 4, 3, 3, 3, 5, 5, 8, 9, 6, 5, 5, 7, 5, 3, 5]

In [61]:
# Input list
my_list = [1, 2, 3, 2, 4, 3, 5, 1]

# Remove duplicates by converting to a set, then back to list
unique_list = list(set(my_list))

print("Original list:", my_list)
print("List after removing duplicates:", unique_list)

Original list: [1, 2, 3, 2, 4, 3, 5, 1]
List after removing duplicates: [1, 2, 3, 4, 5]

In [66]:
l = int(input("Enter the values:"))
l1 = []
for i in l:
    if i not in l2:
        l2.append(i)
    else:
        pass

print(l2)

Enter the values: 3 4 5 6 4 3 6 7 8 9 5 9 7 6 5 4 9

ValueError: invalid literal for int() with base 10: '3 4 5 6 4 3 6 7 8 9 5 9 7 6 5 4 9'

In [67]:
# Take number of rows from user
rows = int(input("Enter number of rows: "))

i = 1  # Initialize counter

while i <= rows:
    print("*" * i)
    i += 1

Enter number of rows:  4

*
**
***
****

In [ ]:
l1 = ["pizza", "burger", "momo", "chowmien", "sandwich", "roll"]
l1 = ["roll", "momo", "sandwich", "burger", "pizza", "chowmien"]
for

## Tuple

In [7]:
for i in range(9):
    i +=1
a = tuple(i)
a

TypeError: 'int' object is not iterable

## Functions

In [5]:
def add3(a,b,c):
    r=a*b*c
    return r

print(add3(2,3,4))

24

In [6]:
print(add3(int(input("Enter 3 numbers:"))))

Enter 3 numbers: 2 3 4

ValueError: invalid literal for int() with base 10: '2 3 4'

In [7]:
#Salary Calculation
def sal(s,a,d):
    print("Your salary is:", s)
    print("Your Allowance is:", a)
    print("Your deduction is:", d)
    net_sal=(s+a)-d
    return net_sal

In [8]:
print(sal(10000,5000,2000))

Your salary is: 10000
Your Allowance is: 5000
Your deduction is: 2000
13000

In [9]:
print(sal(d=2000,s=10000,a=5000))

Your salary is: 10000
Your Allowance is: 5000
Your deduction is: 2000
13000

In [11]:
print(sal(10000,d=2000,a=5000))

Your salary is: 10000
Your Allowance is: 5000
Your deduction is: 2000
13000

In [13]:
def add4(a,b=0,c=0):
    r=a+b+c
    return r

In [14]:
print(add4(10,20,30))

60

In [15]:
print(add4(10))

10

In [28]:
def additem(a,l=[]):
    l.append(a)
    return l

In [29]:
print(additem(4))

[4]

In [30]:
print(additem(5))

[4, 5]

In [31]:
l1=[1,2,3,4]
print(additem(5,l1))

[1, 2, 3, 4, 5]

In [36]:
def additem(a,l=[]):
    l.extend(a)
    return l

In [37]:
print(additem([1,2,3,4,5]))

[1, 2, 3, 4, 5]

In [39]:
print(additem([6]))

[1, 2, 3, 4, 5, 6]

In [42]:
def addn(a,b,/,c,*,d):
    r=a+b+c+d
    return r

In [49]:
print(addn(7,5,c=2,d=1))

15

In [50]:
#Variable length arguents important
def func(*args):
    print(args)

In [51]:
func(40,50,60)

(40, 50, 60)

In [53]:
def func1(a,b,*args):
    print(a,b,args)

In [55]:
func1(40,50,60,70)

40 50 (60, 70)

In [64]:
def func2(a,b,*args,**kwargs):
    print(a,b,args,kwargs)

In [65]:
func2(1,2,3,4,5,c=7,d=8)

1 2 (3, 4, 5) {'c': 7, 'd': 8}

In [67]:
l=[1,2,3,4,5]
itr=iter(l)
print(next(itr))

1

In [68]:
print(next(itr))

2

In [69]:
print(next(itr))

3

In [70]:
print(next(itr))

4

In [71]:
print(next(itr))

5

In [76]:
def days():
    l=["mon","tue","wed","thu","fri","sat","sun"]
    i=0
    while True:
        x=l[i]
        i=(i+1)%7
        yield x

In [77]:
d=days()
print(next(iter(d)))

mon

In [78]:
print(next(iter(d)))

tue

In [79]:
print(next(iter(d)))

wed

In [80]:
print(next(iter(d)))

thu

In [81]:
print(next(iter(d)))

fri

In [82]:
print(next(iter(d)))

sat

In [83]:
print(next(iter(d)))

sun

In [89]:
def months():
    l1=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sept","Oct","Nov","Dec"]
    i=0
    while True:
        x=l1[i]
        i=(i+1)%12
        yield x

In [90]:
m=months()
print(next(iter(m)))

Jan

In [91]:
print(next(iter(m)))

Feb

In [92]:
print(next(iter(m)))

Mar

In [93]:
print(next(iter(m)))

Apr

In [94]:
print(next(iter(m)))

May

In [95]:
print(next(iter(m)))

Jun

In [96]:
print(next(iter(m)))

Jul

In [97]:
print(next(iter(m)))

Aug

In [98]:
print(next(iter(m)))

Sept

In [99]:
print(next(iter(m)))

Oct

In [100]:
print(next(iter(m)))

Nov

In [101]:
print(next(iter(m)))

Dec

In [102]:
print(next(iter(m)))

Jan

## OOP's

## Random Module

In [23]:
import random

Enter the number(1-6): 1

1
The answer is correct

In [54]:
dice = random.randint(1,6)
count = 0
while count<3:
    num = int(input("Guess the number between (1-6):"))
    if dice == num:
        print("Wow, You guessed it right.")
        break
    else:
        print("wrong answer")
        count+=1

Guess the number between (1-6): 3

Behn ke lund galat guess kiya hai

Guess the number between (1-6): 3

Behn ke lund galat guess kiya hai

Guess the number between (1-6): 3

Behn ke lund galat guess kiya hai

## Lambda

In [1]:
add = lambda a,b : a+b
add(1,2)

3

In [3]:
even = lambda n : n%2==0
even(9)

False

In [7]:
l=[1,2,3,4,5,6]
list(map(lambda n : n%2==0,l))

[False, True, False, True, False, True]

In [10]:
l1 = [1,2,3]
l2 = [4,5,6]
list(map(lambda n1,n2 : n1**n2,l1,l2))

[1, 32, 729]

In [14]:
l3=["apple","banana","mango","orange"]
list(map(str.upper,l3))

['APPLE', 'BANANA', 'MANGO', 'ORANGE']

In [18]:
l4=[{"name": "Aman", "age": 20}, {"name": "Suman", "age": 30}]
list(map(lambda n : n["name"], l4))

['Aman', 'Suman']

In [16]:
l4

[{'name': 'Aman', 'age': 20}, {'name': 'Suman', 'age': 30}]

In [21]:
#Filter
def even(num):
    if num%2==0:
        return True
l1=[i for i in range(1,11)]
list(filter(even,l1))

[2, 4, 6, 8, 10]

In [23]:
l5=[i for i in range(1,11)]
list(filter(lambda n : n>5 and n%2==0, l5))

[6, 8, 10]

In [24]:
l4=[{"name": "Aman", "age": 20}, {"name": "Suman", "age": 30},{"name" : "Naman", "age": 28}]
list(filter(lambda n : n["age"]>25, l4))

[{'name': 'Suman', 'age': 30}, {'name': 'Naman', 'age': 28}]

In [25]:
l1 = [{"name" : "Aman", "age": 30}, 
      {"name" : "Riya", "age": 22},
      {"name" : "Karan", "age": 28}]

# Filter using lambda
result = list(filter(lambda x: x["age"] > 25, l1))

# Only keep age key in output
output = [{"age": item["age"]} for item in result]

print(output)

[{'age': 30}, {'age': 28}]

## Numpy

In [26]:
import numpy as np

In [27]:
l=[[1,2,3],[4,5,6]]
arr = np.array(l)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.linspace(1,1.5,10)

array([1.        , 1.05555556, 1.11111111, 1.16666667, 1.22222222,
       1.27777778, 1.33333333, 1.38888889, 1.44444444, 1.5       ])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.random.rand(1)

array([0.31928138])

In [40]:
np.random.randint(1,100)

88

In [42]:
np.random.randint(1,100,3)

array([68,  1, 93], dtype=int32)

In [43]:
arr = np.arange(1,26)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [45]:
arr = arr.reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
arr.shape

(5, 5)

In [47]:
arr.max()

np.int64(25)

In [48]:
arr.min()

np.int64(1)

In [49]:
arr.argmax()

np.int64(24)

In [50]:
arr.argmin()

np.int64(0)

## Pandas

In [5]:
import numpy as np
import pandas as pd

In [2]:
l1 = ["USA", "IND", "CANADA"]

In [3]:
l2 = [123,456,789]

In [9]:
myuser = pd.Series(index = l1, data = l2)

In [10]:
myuser

USA       123
IND       456
CANADA    789
dtype: int64

In [11]:
ages = {"Samay" : 5, "frank":10, "spike":7}

In [12]:
ages

{'Samay': 5, 'frank': 10, 'spike': 7}

In [13]:
pd.Series(ages)

Samay     5
frank    10
spike     7
dtype: int64

In [14]:
dict1 = {"alex": 3000, "bob": 2500, "jimmy": 4000, "jack": 2000}

In [18]:
pd.Series(dict1["bob"])

0    2500
dtype: int64

In [20]:
dict1 = {"alex": 3000, "bob": 2500, "jimmy": 4000, "jack": 2000}
dict2 = {"japan": 40, "india": 50, "china": 30, "USA": 45}

In [21]:
a = pd.Series(dict1)
b=pd.Series(dict2)

In [22]:
a

alex     3000
bob      2500
jimmy    4000
jack     2000
dtype: int64

In [31]:
b["USA"]

np.int64(45)

In [25]:
b[0]

C:\Users\user\AppData\Local\Temp\ipykernel_10968\172979841.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  b[0]

np.int64(40)

In [26]:
b.keys()

Index(['japan', 'india', 'china', 'USA'], dtype='object')

In [29]:
b * 2

japan     80
india    100
china     60
USA       90
dtype: int64

In [30]:
a.add(b, fill_value=0)

USA        45.0
alex     3000.0
bob      2500.0
china      30.0
india      50.0
jack     2000.0
japan      40.0
jimmy    4000.0
dtype: float64

In [6]:
n=np.arange(1,101).reshape(10,10)
n

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [5]:
import numpy as np
import pandas as pd

In [7]:
s=pd.Series("a")
s

0    a
dtype: object

In [2]:
myindex=["a","b","c","d","e","f","g","h","i","j"]

In [7]:
df = pd.DataFrame(data=n,index=myindex)

In [8]:
df

    0   1   2   3   4   5   6   7   8    9
a   1   2   3   4   5   6   7   8   9   10
b  11  12  13  14  15  16  17  18  19   20
c  21  22  23  24  25  26  27  28  29   30
d  31  32  33  34  35  36  37  38  39   40
e  41  42  43  44  45  46  47  48  49   50
f  51  52  53  54  55  56  57  58  59   60
g  61  62  63  64  65  66  67  68  69   70
h  71  72  73  74  75  76  77  78  79   80
i  81  82  83  84  85  86  87  88  89   90
j  91  92  93  94  95  96  97  98  99  100

In [9]:
mycolumn=["jan","feb","mar","apr","may","jun","jul","aug","sep","oct"]

In [10]:
df = pd.DataFrame(data=n,index=myindex, columns=mycolumn)
df

   jan  feb  mar  apr  may  jun  jul  aug  sep  oct
a    1    2    3    4    5    6    7    8    9   10
b   11   12   13   14   15   16   17   18   19   20
c   21   22   23   24   25   26   27   28   29   30
d   31   32   33   34   35   36   37   38   39   40
e   41   42   43   44   45   46   47   48   49   50
f   51   52   53   54   55   56   57   58   59   60
g   61   62   63   64   65   66   67   68   69   70
h   71   72   73   74   75   76   77   78   79   80
i   81   82   83   84   85   86   87   88   89   90
j   91   92   93   94   95   96   97   98   99  100

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10 non-null     int64
 1   1       10 non-null     int64
 2   2       10 non-null     int64
 3   3       10 non-null     int64
 4   4       10 non-null     int64
 5   5       10 non-null     int64
 6   6       10 non-null     int64
 7   7       10 non-null     int64
 8   8       10 non-null     int64
 9   9       10 non-null     int64
dtypes: int64(10)
memory usage: 880.0+ bytes